/**
 * 妆容预设（规则 AR 演示）。
 * 风格说明参考常见美妆内容：清透伪素颜、轻泰混血感、气场红唇、水光苹果肌、通勤豆沙等。
 */

/** @typedef {{
 *   id: string,
 *   name: string,
 *   tagline: string,
 *   styleNote: string,
 *   alphaScale: number,
 *   lipAlpha: number,
 *   vividMul: number,
 *   blushMul: number,
 *   contourMul: number,
 *   browMul: number,
 *   highlightMul: number,
 *   lipRgbMix: [number, number, number],
 *   lipRgbMixT: number,
 *   blushRgbMix: [number, number, number],
 *   blushRgbMixT: number,
 *   browRgbMix: [number, number, number],
 *   browRgbMixT: number,
 *   browThicknessMul: number,
 *   browLiftExtra: number,
 *   contourLineWidthMul: number,
 *   blushRadiusMul: number,
 *   highlightRadiusMul: number,
 *   foundationMul: number,
 *   outlineOpacity: number,
 *   demoMakeupOpacity: number,
 *   outlineWhenLip: number,
 * }} MakeupLookPreset */

/** 滑杆 0～100 → 叠层强度倍率 */
export function sliderToStrength(slider0to100) {
  const t = Math.max(0, Math.min(100, slider0to100)) / 100;
  return 0.22 + t * t * 1.12;
}

/** @type {MakeupLookPreset[]} */
export const LOOK_PRESETS = [
  {
    id: 'plain_water',
    name: '白开水妆',
    tagline: '清透伪素颜、低饱和留白',
    styleNote:
      '参考「白开水妆」：哑光清透底妆感、低饱和裸粉/奶茶唇、野生毛流眉、修容极轻；整体做减法，像水一样干净不抢眼。',
    alphaScale: 0.76,
    lipAlpha: 0.19,
    vividMul: 0.86,
    blushMul: 0.38,
    contourMul: 0.32,
    browMul: 0.3,
    highlightMul: 0.48,
    lipRgbMix: [225, 198, 200],
    lipRgbMixT: 0.16,
    blushRgbMix: [255, 220, 222],
    blushRgbMixT: 0.12,
    browRgbMix: [120, 108, 102],
    browRgbMixT: 0.06,
    browThicknessMul: 0.84,
    browLiftExtra: -0.0014,
    contourLineWidthMul: 0.58,
    blushRadiusMul: 0.88,
    highlightRadiusMul: 0.85,
    foundationMul: 1.06,
    outlineOpacity: 0.4,
    demoMakeupOpacity: 0.38,
    outlineWhenLip: 0.24,
  },
  {
    id: 'light_thai',
    name: '轻泰妆',
    tagline: '混血立体、野生眉、奶茶腮红',
    styleNote:
      '参考「轻泰妆」：眉峰微挑、根根野生毛流感；腮红偏大范围、奶茶/杏橘色扫颧骨与苹果肌；修容略加强立体，唇偏暖橘棕。',
    alphaScale: 1,
    lipAlpha: 0.35,
    vividMul: 1.08,
    blushMul: 1.12,
    contourMul: 0.9,
    browMul: 0.78,
    highlightMul: 0.92,
    lipRgbMix: [218, 128, 105],
    lipRgbMixT: 0.14,
    blushRgbMix: [255, 165, 130],
    blushRgbMixT: 0.26,
    browRgbMix: [125, 92, 72],
    browRgbMixT: 0.22,
    browThicknessMul: 1.16,
    browLiftExtra: 0.0022,
    contourLineWidthMul: 1.08,
    blushRadiusMul: 1.12,
    highlightRadiusMul: 1.04,
    foundationMul: 0.96,
    outlineOpacity: 0.54,
    demoMakeupOpacity: 0.56,
    outlineWhenLip: 0.34,
  },
  {
    id: 'cool_sister',
    name: '御姐妆',
    tagline: '轮廓利落、红唇气场',
    styleNote:
      '参考「御姐/气场妆」：修容与下颌线更清晰，眉形略实、唇色饱和（玫瑰/酒红倾向），腮红退为辅助、强调冷艳利落感。',
    alphaScale: 1.14,
    lipAlpha: 0.48,
    vividMul: 1.16,
    blushMul: 0.68,
    contourMul: 1.26,
    browMul: 0.92,
    highlightMul: 0.82,
    lipRgbMix: [165, 58, 88],
    lipRgbMixT: 0.16,
    blushRgbMix: [210, 115, 128],
    blushRgbMixT: 0.08,
    browRgbMix: [82, 68, 64],
    browRgbMixT: 0.14,
    browThicknessMul: 1.08,
    browLiftExtra: 0.001,
    contourLineWidthMul: 1.38,
    blushRadiusMul: 0.9,
    highlightRadiusMul: 1.06,
    foundationMul: 0.9,
    outlineOpacity: 0.72,
    demoMakeupOpacity: 0.78,
    outlineWhenLip: 0.46,
  },
  {
    id: 'dewy_kr',
    name: '水光韩妆',
    tagline: '苹果肌腮红、光泽唇、高光明显',
    styleNote:
      '参考韩系水光/果汁感：腮红量感明显、偏粉或珊瑚色团在苹果肌；高光偏亮营造水光；修容相对柔和，唇偏亮粉玻璃感。',
    alphaScale: 0.95,
    lipAlpha: 0.33,
    vividMul: 1.1,
    blushMul: 1.32,
    contourMul: 0.6,
    browMul: 0.46,
    highlightMul: 0.92,
    lipRgbMix: [240, 125, 142],
    lipRgbMixT: 0.11,
    blushRgbMix: [255, 138, 152],
    blushRgbMixT: 0.28,
    browRgbMix: [112, 94, 88],
    browRgbMixT: 0.05,
    browThicknessMul: 0.94,
    browLiftExtra: -0.0004,
    contourLineWidthMul: 0.74,
    blushRadiusMul: 1.2,
    highlightRadiusMul: 1.18,
    foundationMul: 1.04,
    outlineOpacity: 0.5,
    demoMakeupOpacity: 0.52,
    outlineWhenLip: 0.32,
  },
  {
    id: 'commute',
    name: '通勤气质',
    tagline: '豆沙玫瑰、大地协调、低调专业',
    styleNote:
      '参考「通勤/OL 妆」：底妆感干净、眼颊同色系偏大地；唇用豆沙/玫瑰低调显气色；修容与眉自然不过度，适合日常职场。',
    alphaScale: 0.88,
    lipAlpha: 0.27,
    vividMul: 0.97,
    blushMul: 0.86,
    contourMul: 0.76,
    browMul: 0.54,
    highlightMul: 0.8,
    lipRgbMix: [198, 128, 138],
    lipRgbMixT: 0.1,
    blushRgbMix: [238, 168, 158],
    blushRgbMixT: 0.15,
    browRgbMix: [106, 90, 84],
    browRgbMixT: 0.1,
    browThicknessMul: 0.98,
    browLiftExtra: -0.0006,
    contourLineWidthMul: 0.9,
    blushRadiusMul: 0.98,
    highlightRadiusMul: 0.94,
    foundationMul: 1,
    outlineOpacity: 0.46,
    demoMakeupOpacity: 0.45,
    outlineWhenLip: 0.28,
  },
];

export const DEFAULT_LOOK_ID = 'plain_water';

export const DEFAULT_LOOK_SLIDER = 72;

/** @param {string} [id] */
export function getLookPreset(id) {
  const p = LOOK_PRESETS.find((x) => x.id === id);
  return p || LOOK_PRESETS.find((x) => x.id === DEFAULT_LOOK_ID) || LOOK_PRESETS[0];
}
